# @package _global_
defaults:
  - libero_ar
  - override /data: libero_local
  - _self_
datastatics_path: ${oc.env:PROJECT_ROOT}/data/stats/libero_local_stats.json
model:
  pretrained_ckpt: checkpoints/g05-base/checkpoints/model_state_dict.pt
tokenizer:
  vq_config:
    ckpt_dir: checkpoints/action_tokenizer.pt
